appPort: :8080
metricPort: :9090

backends:
  - http://backend1:5678
  - http://backend2:5678
  - http://backend3:5678

heartbeat:
  interval: 5
  clientTimeout: 1
  backends:
    - http://backend1:5678/healthz
    - http://backend2:5678/healthz
    - http://backend3:5678/healthz
logger:
  env: "local"
  level: "debug"
  filename: "app.log"
  maxSize: 200
  maxBackups: 10
  maxAge: 30

