appPort: :8080
metricPort: :9090

backends:
  - http://backend1
  - http://backend2
  - http://backend3

heartbeat:
  interval: 5
  clientTimeout: 1
  backends:
    - http://backend1/healthz
    - http://backend2/healthz
    - http://backend3/healthz
logger:
  env: "local"
  level: "debug"
  filename: "app.log"
  maxSize: 200
  maxBackups: 10
  maxAge: 30

