port: 8080
backends:
  - http://localhost:9997
  - http://localhost:9998
  - http://localhost:9999


heartbeat:
  interval: 5
  clientTimeout: 1
  backends:
    - http://localhost:9997/healthz
    - http://localhost:9998/healthz
    - http://localhost:9999/healthz
#  retries: 3
#  backoff: 2s
#  maxBackoff: 10s
#  jitter: true
logger:
  env: "local"
  level: "debug"
  filename: "app.log"
  maxSize: 200
  maxBackups: 10
  maxAge: 30

